import type { TransitionPack, TransitionPackId } from '../../lib/types';

export const TRANSITION_PACKS: Record<TransitionPackId, TransitionPack> = {
  'smooth-zoom': {
    id: 'smooth-zoom',
    name: 'Smooth Zoom',
    description: 'Gentle Ken Burns with soft fade transitions',
    entryFrames: 22,
    exitFrames: 22,
    flashOpacity: 0,
    motionScaleBg: 0.15,
    motionScaleFg: 0.03,
    springDamping: 22,
    springStiffness: 150,
    motionSequence: ['zoom-in', 'pan-right', 'zoom-out', 'pan-left', 'pan-up'],
    blurOnEntry: false,
  },
  'swipe-slide': {
    id: 'swipe-slide',
    name: 'Swipe / Slide',
    description: 'Directional slide with light flash',
    entryFrames: 18,
    exitFrames: 18,
    flashOpacity: 0.18,
    motionScaleBg: 0.10,
    motionScaleFg: 0.02,
    springDamping: 20,
    springStiffness: 180,
    motionSequence: ['pan-left', 'pan-right', 'zoom-in', 'pan-up', 'pan-down'],
    blurOnEntry: false,
  },
  'flash-cut': {
    id: 'flash-cut',
    name: 'Flash Cut',
    description: 'Quick cuts with white flash — CapCut signature',
    entryFrames: 13,
    exitFrames: 13,
    flashOpacity: 0.55,
    motionScaleBg: 0.18,
    motionScaleFg: 0.04,
    springDamping: 15,
    springStiffness: 250,
    motionSequence: ['zoom-in', 'zoom-out', 'pan-left', 'zoom-in', 'pan-right'],
    blurOnEntry: false,
  },
  'blur-snap': {
    id: 'blur-snap',
    name: 'Blur Snap',
    description: 'Motion blur on entry then snaps into focus',
    entryFrames: 16,
    exitFrames: 16,
    flashOpacity: 0.20,
    motionScaleBg: 0.20,
    motionScaleFg: 0.05,
    springDamping: 12,
    springStiffness: 300,
    motionSequence: ['zoom-in', 'pan-right', 'zoom-out', 'pan-left', 'zoom-in'],
    blurOnEntry: true,
  },
  'ken-burns-premium': {
    id: 'ken-burns-premium',
    name: 'Ken Burns Premium',
    description: 'Cinematic slow pan & zoom — no hard cuts',
    entryFrames: 28,
    exitFrames: 28,
    flashOpacity: 0,
    motionScaleBg: 0.22,
    motionScaleFg: 0.06,
    springDamping: 28,
    springStiffness: 120,
    motionSequence: ['zoom-in', 'pan-right', 'zoom-out', 'pan-left', 'pan-up'],
    blurOnEntry: false,
  },
  'fast-punchy': {
    id: 'fast-punchy',
    name: 'Fast Punchy',
    description: 'High-energy cuts with impact zoom bursts',
    entryFrames: 10,
    exitFrames: 10,
    flashOpacity: 0.60,
    motionScaleBg: 0.25,
    motionScaleFg: 0.06,
    springDamping: 10,
    springStiffness: 350,
    motionSequence: ['zoom-in', 'zoom-out', 'zoom-in', 'pan-left', 'zoom-in'],
    blurOnEntry: true,
  },
  'minimal-clean': {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Barely-there motion — pure elegance for luxury',
    entryFrames: 24,
    exitFrames: 24,
    flashOpacity: 0,
    motionScaleBg: 0.08,
    motionScaleFg: 0.02,
    springDamping: 32,
    springStiffness: 100,
    motionSequence: ['zoom-in', 'pan-right', 'pan-left', 'zoom-out', 'pan-up'],
    blurOnEntry: false,
  },
};
