import type { StylePreset, PresetId } from './types';

export const PRESETS: Record<PresetId, StylePreset> = {
  'clean-dealer': {
    id: 'clean-dealer',
    name: 'Clean Dealer',
    description: 'Professional, trustworthy, broad appeal',
    emoji: '🏢',
    tone: 'confident',
    ctaMode: 'visit-today',
    hookStyle: 'direct, clear opener that highlights vehicle value and builds trust — no hype',
    transitionPackId: 'smooth-zoom',
    defaultPaletteId: 'classic-blue-white',
    pacing: 'medium',
    hookFontSize: 42,
    titleFontSize: 60,
    priceFontSize: 44,
    featureFontSize: 28,
    gradientStyle: 'cinematic',
    priceStyle: 'badge',
    hookTextStyle: 'caps',
  },
  'luxury': {
    id: 'luxury',
    name: 'Luxury',
    description: 'Premium, refined, aspirational',
    emoji: '✨',
    tone: 'premium',
    ctaMode: 'book-test-drive',
    hookStyle: 'sophisticated, experience-led opener — emphasize exclusivity, craftsmanship, or lifestyle',
    transitionPackId: 'minimal-clean',
    defaultPaletteId: 'black-gold',
    pacing: 'slow',
    hookFontSize: 38,
    titleFontSize: 54,
    priceFontSize: 40,
    featureFontSize: 26,
    gradientStyle: 'luxury',
    priceStyle: 'large-text',
    hookTextStyle: 'mixed',
  },
  'truck-tough': {
    id: 'truck-tough',
    name: 'Truck Tough',
    description: 'Bold, capable, built for work and play',
    emoji: '🛻',
    tone: 'confident',
    ctaMode: 'visit-today',
    hookStyle: 'bold, capability-focused opener for truck buyers — highlight towing, payload, terrain, or lifestyle without exaggerating',
    transitionPackId: 'flash-cut',
    defaultPaletteId: 'truck-yellow-charcoal',
    pacing: 'fast',
    hookFontSize: 46,
    titleFontSize: 64,
    priceFontSize: 46,
    featureFontSize: 30,
    gradientStyle: 'bold',
    priceStyle: 'badge',
    hookTextStyle: 'caps',
  },
  'family-suv': {
    id: 'family-suv',
    name: 'Family SUV',
    description: 'Safe, spacious, built for real life',
    emoji: '👨‍👩‍👧‍👦',
    tone: 'friendly',
    ctaMode: 'book-test-drive',
    hookStyle: 'warm, practical opener for families — highlight safety, space, comfort, or everyday reliability',
    transitionPackId: 'smooth-zoom',
    defaultPaletteId: 'classic-blue-white',
    pacing: 'medium',
    hookFontSize: 40,
    titleFontSize: 58,
    priceFontSize: 42,
    featureFontSize: 28,
    gradientStyle: 'cinematic',
    priceStyle: 'badge',
    hookTextStyle: 'sentence',
  },
  'budget-value': {
    id: 'budget-value',
    name: 'Budget / Value',
    description: 'Affordable, smart, price-forward',
    emoji: '💰',
    tone: 'practical',
    ctaMode: 'ask-financing',
    hookStyle: 'straightforward value-focused opener — lead with price, affordability, or financing. No fake urgency.',
    transitionPackId: 'fast-punchy',
    defaultPaletteId: 'bold-red-black',
    pacing: 'fast',
    hookFontSize: 44,
    titleFontSize: 62,
    priceFontSize: 48,
    featureFontSize: 28,
    gradientStyle: 'bold',
    priceStyle: 'badge',
    hookTextStyle: 'caps',
  },
  'performance': {
    id: 'performance',
    name: 'Performance',
    description: 'Fast, driver-focused, exciting',
    emoji: '🏎️',
    tone: 'confident',
    ctaMode: 'book-test-drive',
    hookStyle: 'adrenaline-aware, driver-focused opener — speak to enthusiasts through performance specs or the driving feel',
    transitionPackId: 'flash-cut',
    defaultPaletteId: 'bold-red-black',
    pacing: 'punchy',
    hookFontSize: 44,
    titleFontSize: 62,
    priceFontSize: 44,
    featureFontSize: 28,
    gradientStyle: 'bold',
    priceStyle: 'pill',
    hookTextStyle: 'caps',
  },
  'bilingual-lite': {
    id: 'bilingual-lite',
    name: 'Bilingual',
    description: 'English + Spanish, warm & welcoming',
    emoji: '🌎',
    tone: 'bilingual-lite',
    ctaMode: 'call',
    hookStyle: 'warm, welcoming opener in English with a short natural Spanish phrase or word — accessible to Spanish-speaking buyers without being forced',
    transitionPackId: 'smooth-zoom',
    defaultPaletteId: 'warm-orange',
    pacing: 'medium',
    hookFontSize: 38,
    titleFontSize: 56,
    priceFontSize: 42,
    featureFontSize: 26,
    gradientStyle: 'cinematic',
    priceStyle: 'badge',
    hookTextStyle: 'mixed',
  },
};

export const PRESET_ORDER: PresetId[] = [
  'clean-dealer', 'luxury', 'truck-tough', 'family-suv',
  'budget-value', 'performance', 'bilingual-lite',
];
